"""auto

Revision ID: 304c3e63da00
Revises: 
Create Date: 2026-08-28 15:52:38.980749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304c3e63da00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ADMINISTRADOR', 'MEDICO', 'ENFERMEIRO', 'TECNICO_ENFERMAGEM', 'FARMACEUTICO', 'RECEPCIONISTA', 'FATURAMENTO', 'FINANCEIRO', 'ALMOXARIFE', 'NUTRICIONISTA', 'FISIOTERAPEUTA', 'ASSISTENTE_SOCIAL', 'LABORATORISTA', 'RADIOLOGISTA', 'GESTOR', name='tipoperfil'), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissoes_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissoes_modulo'), ['modulo'], unique=False)

    op.create_table('perfil_permissao',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('conselho_tipo', sa.String(length=10), nullable=True),
    sa.Column('conselho_numero', sa.String(length=30), nullable=True),
    sa.Column('conselho_uf', sa.String(length=2), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('cert_digital_path', sa.String(length=500), nullable=True),
    sa.Column('cert_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'BLOQUEADO', name='statususuario'), nullable=False),
    sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('perfil_permissao')
    with op.batch_alter_table('permissoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissoes_modulo'))
        batch_op.drop_index(batch_op.f('ix_permissoes_codigo'))

    op.drop_table('permissoes')
    op.drop_table('perfis')
    # ### end Alembic commands ###
