"""add fase 6 gestao e compliance (residuos pgrss, rnds fhir)

Revision ID: 352f70fe1d77
Revises: f26b8ccb9b91
Create Date: 2026-08-28 19:42:55.195772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352f70fe1d77'
down_revision = 'f26b8ccb9b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coletas_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('empresa_coletora', sa.String(length=200), nullable=False),
    sa.Column('numero_manifesto', sa.String(length=50), nullable=True),
    sa.Column('peso_total_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('destinacao_final', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coletas_residuo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coletas_residuo_coletado_em'), ['coletado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_coletas_residuo_numero'), ['numero'], unique=True)

    op.create_table('registros_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Enum('A', 'B', 'C', 'D', 'E', name='gruporesiduo'), nullable=False),
    sa.Column('origem_setor', sa.String(length=100), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('acondicionamento', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ARMAZENADO', 'COLETADO', 'DESTINADO', name='statuscoleta'), nullable=False),
    sa.Column('coleta_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coleta_id'], ['coletas_residuo.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_residuo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_residuo_gerado_em'), ['gerado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_residuo_grupo'), ['grupo'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_residuo_status'), ['status'], unique=False)

    op.create_table('registros_rnds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_recurso', sa.Enum('PACIENTE', 'ATENDIMENTO', 'RESULTADO_EXAME', 'IMUNIZACAO', 'PRESCRICAO', 'CONDICAO', name='tiporecursofhir'), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('origem_tipo', sa.String(length=50), nullable=True),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('payload_fhir', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIANDO', 'ENVIADO', 'ERRO', 'CANCELADO', name='statusenviornds'), nullable=False),
    sa.Column('protocolo_rnds', sa.String(length=100), nullable=True),
    sa.Column('mensagem_retorno', sa.Text(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_rnds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_rnds_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rnds_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rnds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rnds_tipo_recurso'), ['tipo_recurso'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_rnds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_rnds_tipo_recurso'))
        batch_op.drop_index(batch_op.f('ix_registros_rnds_status'))
        batch_op.drop_index(batch_op.f('ix_registros_rnds_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_registros_rnds_criado_em'))

    op.drop_table('registros_rnds')
    with op.batch_alter_table('registros_residuo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_residuo_status'))
        batch_op.drop_index(batch_op.f('ix_registros_residuo_grupo'))
        batch_op.drop_index(batch_op.f('ix_registros_residuo_gerado_em'))

    op.drop_table('registros_residuo')
    with op.batch_alter_table('coletas_residuo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coletas_residuo_numero'))
        batch_op.drop_index(batch_op.f('ix_coletas_residuo_coletado_em'))

    op.drop_table('coletas_residuo')
    # ### end Alembic commands ###
