"""auto

Revision ID: 37c4a89147dd
Revises: 304c3e63da00
Create Date: 2026-08-28 16:16:07.643112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c4a89147dd'
down_revision = '304c3e63da00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas_ambulatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('dia_semana', sa.Enum('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO', name='diasemana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('duracao_consulta_min', sa.Integer(), nullable=False),
    sa.Column('vagas_total', sa.Integer(), nullable=False),
    sa.Column('vagas_reserva', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendas_ambulatorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendas_ambulatorio_medico_id'), ['medico_id'], unique=False)

    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_social', sa.String(length=200), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', 'INDEFINIDO', name='sexo'), nullable=False),
    sa.Column('raca_cor', sa.Enum('BRANCA', 'PRETA', 'PARDA', 'AMARELA', 'INDIGENA', 'NAO_DECLARADO', name='racacor'), nullable=True),
    sa.Column('estado_civil', sa.Enum('SOLTEIRO', 'CASADO', 'UNIAO_ESTAVEL', 'DIVORCIADO', 'VIUVO', 'SEPARADO', 'NAO_INFORMADO', name='estadocivil'), nullable=True),
    sa.Column('naturalidade', sa.String(length=100), nullable=True),
    sa.Column('nacionalidade', sa.String(length=60), nullable=True),
    sa.Column('tipo_sanguineo', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'DESCONHECIDO', name='tiposanguineo'), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'OBITO', 'INATIVO', name='statuspaciente'), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=20), nullable=True),
    sa.Column('rg_uf', sa.String(length=2), nullable=True),
    sa.Column('cns', sa.String(length=20), nullable=True),
    sa.Column('cns_provisorio', sa.String(length=20), nullable=True),
    sa.Column('certidao_nascimento', sa.String(length=40), nullable=True),
    sa.Column('titulo_eleitor', sa.String(length=20), nullable=True),
    sa.Column('plano_saude', sa.String(length=100), nullable=True),
    sa.Column('numero_carteirinha', sa.String(length=50), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('observacoes_clinicas', sa.Text(), nullable=True),
    sa.Column('data_obito', sa.Date(), nullable=True),
    sa.Column('causa_obito', sa.String(length=300), nullable=True),
    sa.Column('escolaridade', sa.String(length=60), nullable=True),
    sa.Column('ocupacao', sa.String(length=100), nullable=True),
    sa.Column('religiao', sa.String(length=60), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('tipo_logradouro', sa.Enum('RUA', 'AVENIDA', 'TRAVESSA', 'ALAMEDA', 'ESTRADA', 'RODOVIA', 'SITIO', 'FAZENDA', 'OUTROS', name='tipologradouro'), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('zona', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=200), nullable=True),
    sa.Column('responsavel_grau', sa.String(length=50), nullable=True),
    sa.Column('responsavel_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_telefone', sa.String(length=20), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('nome_pai', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_cns'), ['cns'], unique=True)
        batch_op.create_index(batch_op.f('ix_pacientes_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_pacientes_data_nascimento'), ['data_nascimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_pacientes_nome'), ['nome'], unique=False)

    op.create_table('atendimentos_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('chegada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('modo_chegada', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO_TRIAGEM', 'TRIADO', 'EM_ATENDIMENTO', 'AGUARDANDO_RESULTADO', 'FINALIZADO', name='statusatendimentoemergencia'), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('inicio_atendimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hipotese_diagnostica', sa.String(length=500), nullable=True),
    sa.Column('cid10_principal', sa.String(length=10), nullable=True),
    sa.Column('conduta', sa.Text(), nullable=True),
    sa.Column('anamnese', sa.Text(), nullable=True),
    sa.Column('exame_fisico', sa.Text(), nullable=True),
    sa.Column('saida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_saida', sa.Enum('ALTA_MEDICA', 'INTERNACAO', 'TRANSFERENCIA', 'OBITO', 'EVASAO', 'RECUSA_ATENDIMENTO', name='motivosaidaemergencia'), nullable=True),
    sa.Column('destino_internacao', sa.String(length=100), nullable=True),
    sa.Column('destino_transferencia', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atendimentos_emergencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_emergencia_chegada_em'), ['chegada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_emergencia_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_atendimentos_emergencia_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_emergencia_status'), ['status'], unique=False)

    op.create_table('consultas_ambulatoriais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('PRIMEIRA_VEZ', 'RETORNO', 'URGENCIA', 'PROCEDIMENTO', name='tipoconsulta'), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'CONFIRMADA', 'EM_ATENDIMENTO', 'REALIZADA', 'FALTA', 'CANCELADA', 'REMARCADA', name='statusconsulta'), nullable=False),
    sa.Column('agendado_por_id', sa.Integer(), nullable=True),
    sa.Column('agendado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes_agendamento', sa.String(length=300), nullable=True),
    sa.Column('inicio_atendimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fim_atendimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anamnese', sa.Text(), nullable=True),
    sa.Column('exame_fisico', sa.Text(), nullable=True),
    sa.Column('hipotese_diagnostica', sa.String(length=500), nullable=True),
    sa.Column('cid10_principal', sa.String(length=10), nullable=True),
    sa.Column('cid10_secundario', sa.String(length=10), nullable=True),
    sa.Column('conduta', sa.Text(), nullable=True),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('pressao_sistolica', sa.Integer(), nullable=True),
    sa.Column('pressao_diastolica', sa.Integer(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('altura', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('retorno_data', sa.Date(), nullable=True),
    sa.Column('retorno_dias', sa.Integer(), nullable=True),
    sa.Column('procedimento_sus', sa.String(length=10), nullable=True),
    sa.Column('cbo_medico', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas_ambulatorio.id'], ),
    sa.ForeignKeyConstraint(['agendado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas_ambulatoriais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_ambulatoriais_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_ambulatoriais_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_consultas_ambulatoriais_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aberto_por_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prontuarios_numero'), ['numero'], unique=True)

    op.create_table('entradas_prontuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ANAMNESE', 'EVOLUCAO_MEDICA', 'EVOLUCAO_ENFERMAGEM', 'PRESCRICAO_MEDICA', 'PRESCRICAO_ENFERMAGEM', 'RESULTADO_EXAME', 'LAUDO', 'ALTA', 'TRANSFERENCIA', 'OBITO', 'NOTA_CIRURGICA', 'RECEITUARIO', 'ATESTADO', 'OUTRO', name='tipoentradaprontuario'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinado_por_id', sa.Integer(), nullable=True),
    sa.Column('assinatura_hash', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assinado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entradas_prontuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entradas_prontuario_prontuario_id'), ['prontuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entradas_prontuario_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('triagens_manchester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('queixa_principal', sa.String(length=500), nullable=False),
    sa.Column('discriminador', sa.String(length=200), nullable=True),
    sa.Column('classificacao', sa.Enum('VERMELHO', 'LARANJA', 'AMARELO', 'VERDE', 'AZUL', name='classificacaomanchester'), nullable=False),
    sa.Column('pressao_sistolica', sa.Integer(), nullable=True),
    sa.Column('pressao_diastolica', sa.Integer(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frequencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('saturacao_o2', sa.Integer(), nullable=True),
    sa.Column('glicemia_capilar', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('altura', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('escala_dor', sa.Integer(), nullable=True),
    sa.Column('realizada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('realizada_por_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos_emergencia.id'], ),
    sa.ForeignKeyConstraint(['realizada_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triagens_manchester', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triagens_manchester_atendimento_id'), ['atendimento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triagens_manchester', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triagens_manchester_atendimento_id'))

    op.drop_table('triagens_manchester')
    with op.batch_alter_table('entradas_prontuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entradas_prontuario_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_entradas_prontuario_prontuario_id'))

    op.drop_table('entradas_prontuario')
    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prontuarios_numero'))

    op.drop_table('prontuarios')
    with op.batch_alter_table('consultas_ambulatoriais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_ambulatoriais_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_consultas_ambulatoriais_numero'))
        batch_op.drop_index(batch_op.f('ix_consultas_ambulatoriais_data'))

    op.drop_table('consultas_ambulatoriais')
    with op.batch_alter_table('atendimentos_emergencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_emergencia_status'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_emergencia_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_emergencia_numero'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_emergencia_chegada_em'))

    op.drop_table('atendimentos_emergencia')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_nome'))
        batch_op.drop_index(batch_op.f('ix_pacientes_data_nascimento'))
        batch_op.drop_index(batch_op.f('ix_pacientes_cpf'))
        batch_op.drop_index(batch_op.f('ix_pacientes_cns'))

    op.drop_table('pacientes')
    with op.batch_alter_table('agendas_ambulatorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendas_ambulatorio_medico_id'))

    op.drop_table('agendas_ambulatorio')
    # ### end Alembic commands ###
