"""add internacao module (leitos, internacoes, prescricoes, controles, evolucoes)

Revision ID: 5a50c2fd4cf2
Revises: 37c4a89147dd
Create Date: 2026-08-28 17:08:21.494470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a50c2fd4cf2'
down_revision = '37c4a89147dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('ENFERMARIA', 'UTI_ADULTO', 'UTI_NEONATAL', 'ISOLAMENTO', 'MATERNIDADE', 'PEDIATRIA', 'OBSERVACAO', 'CIRURGICO', 'SEMI_INTENSIVO', name='tipoleito'), nullable=False),
    sa.Column('andar', sa.String(length=20), nullable=True),
    sa.Column('ala', sa.String(length=50), nullable=True),
    sa.Column('quarto', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADO', 'RESERVADO', 'LIMPEZA', 'MANUTENCAO', 'BLOQUEADO', name='statusleito'), nullable=False),
    sa.Column('isolamento', sa.Boolean(), nullable=False),
    sa.Column('motivo_bloqueio', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leitos_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_leitos_status'), ['status'], unique=False)

    op.create_table('internacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('leito_id', sa.Integer(), nullable=False),
    sa.Column('medico_responsavel_id', sa.Integer(), nullable=False),
    sa.Column('admissao_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.Enum('ELETIVA', 'URGENCIA', 'EMERGENCIA', 'OBSTETRICIA', 'PSIQUIATRIA', name='tipointernacao'), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('hipotese_diagnostica', sa.String(length=500), nullable=True),
    sa.Column('cid10_principal', sa.String(length=10), nullable=True),
    sa.Column('cid10_secundario', sa.String(length=10), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('numero_aih', sa.String(length=20), nullable=True),
    sa.Column('admitido_por_id', sa.Integer(), nullable=True),
    sa.Column('observacoes_admissao', sa.Text(), nullable=True),
    sa.Column('origem_pa', sa.Boolean(), nullable=True),
    sa.Column('atendimento_emergencia_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'ALTA', 'TRANSFERIDA', 'OBITO', name='statusinternacao'), nullable=False),
    sa.Column('alta_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_alta', sa.Enum('ALTA_MEDICA', 'ALTA_A_PEDIDO', 'TRANSFERENCIA', 'OBITO', 'EVASAO', 'ALTA_ADMINISTRATIVA', name='tipoalta'), nullable=True),
    sa.Column('condicao_alta', sa.Enum('CURADO', 'MELHORADO', 'INALTERADO', 'PIORADO', 'OBITO', name='condicaoalta'), nullable=True),
    sa.Column('diagnostico_principal_alta', sa.String(length=500), nullable=True),
    sa.Column('resumo_alta', sa.Text(), nullable=True),
    sa.Column('orientacoes_alta', sa.Text(), nullable=True),
    sa.Column('retorno_dias', sa.Integer(), nullable=True),
    sa.Column('alta_assinada', sa.Boolean(), nullable=True),
    sa.Column('alta_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('dado_alta_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admitido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['atendimento_emergencia_id'], ['atendimentos_emergencia.id'], ),
    sa.ForeignKeyConstraint(['dado_alta_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['leito_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['medico_responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internacoes_admissao_em'), ['admissao_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacoes_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_internacoes_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('controles_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('pressao_sistolica', sa.Integer(), nullable=True),
    sa.Column('pressao_diastolica', sa.Integer(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frequencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('saturacao_o2', sa.Integer(), nullable=True),
    sa.Column('glicemia_capilar', sa.Integer(), nullable=True),
    sa.Column('escala_dor', sa.Integer(), nullable=True),
    sa.Column('nivel_consciencia', sa.String(length=50), nullable=True),
    sa.Column('soro_ev', sa.Integer(), nullable=True),
    sa.Column('medicacao_ev', sa.Integer(), nullable=True),
    sa.Column('ingesta_oral', sa.Integer(), nullable=True),
    sa.Column('outros_entrada', sa.Integer(), nullable=True),
    sa.Column('diurese', sa.Integer(), nullable=True),
    sa.Column('drenos', sa.Integer(), nullable=True),
    sa.Column('vomitos', sa.Integer(), nullable=True),
    sa.Column('outros_saida', sa.Integer(), nullable=True),
    sa.Column('evacuacao', sa.Boolean(), nullable=True),
    sa.Column('evacuacao_caracteristicas', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controles_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controles_paciente_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_controles_paciente_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('evolucoes_enfermagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('assinada', sa.Boolean(), nullable=True),
    sa.Column('assinada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_hash', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolucoes_enfermagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolucoes_enfermagem_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolucoes_enfermagem_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('evolucoes_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subjetivo', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('avaliacao', sa.Text(), nullable=True),
    sa.Column('plano', sa.Text(), nullable=True),
    sa.Column('evolucao_livre', sa.Text(), nullable=True),
    sa.Column('cid10_atual', sa.String(length=10), nullable=True),
    sa.Column('assinada', sa.Boolean(), nullable=False),
    sa.Column('assinada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_hash', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolucoes_medicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolucoes_medicas_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolucoes_medicas_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('prescricoes_enfermagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('enfermeiro_id', sa.Integer(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('assinada', sa.Boolean(), nullable=True),
    sa.Column('assinada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_hash', sa.String(length=512), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enfermeiro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescricoes_enfermagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_enfermagem_internacao_id'), ['internacao_id'], unique=False)

    op.create_table('prescricoes_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=False),
    sa.Column('validade_horas', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('assinada', sa.Boolean(), nullable=False),
    sa.Column('assinada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_hash', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescricoes_medicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_medicas_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_medicas_numero'), ['numero'], unique=True)

    op.create_table('transferencias_leito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('leito_origem_id', sa.Integer(), nullable=False),
    sa.Column('leito_destino_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('realizada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('realizada_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['leito_destino_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['leito_origem_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['realizada_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MEDICAMENTO', 'SOLUCAO', 'DIETA', 'CUIDADO', 'PROCEDIMENTO', 'CONSULTORIA', 'EXAME', 'HEMODERIVADO', name='tipoitemprescricao'), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('via', sa.Enum('ORAL', 'ENDOVENOSA', 'INTRAMUSCULAR', 'SUBCUTANEA', 'SUBLINGUAL', 'INALATORIA', 'TOPICA', 'RETAL', 'NASAL', 'OCULAR', 'SONDA', 'OUTRO', name='viaadministracao'), nullable=True),
    sa.Column('frequencia', sa.Enum('UNICA', 'SE_NECESSARIO', 'CADA_4H', 'CADA_6H', 'CADA_8H', 'CADA_12H', 'CADA_24H', 'CADA_48H', 'CONTINUO', 'OUTRO', name='frequenciaadministracao'), nullable=True),
    sa.Column('frequencia_custom', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=100), nullable=True),
    sa.Column('horarios', sa.String(length=200), nullable=True),
    sa.Column('diluicao', sa.String(length=200), nullable=True),
    sa.Column('velocidade_infusao', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'CONCLUIDO', 'CANCELADO', name='statusitemprescricao'), nullable=False),
    sa.Column('suspenso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspenso_motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes_medicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_prescricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_prescricao_prescricao_id'), ['prescricao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_prescricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_prescricao_prescricao_id'))

    op.drop_table('itens_prescricao')
    op.drop_table('transferencias_leito')
    with op.batch_alter_table('prescricoes_medicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_medicas_numero'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_medicas_internacao_id'))

    op.drop_table('prescricoes_medicas')
    with op.batch_alter_table('prescricoes_enfermagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_enfermagem_internacao_id'))

    op.drop_table('prescricoes_enfermagem')
    with op.batch_alter_table('evolucoes_medicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolucoes_medicas_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_evolucoes_medicas_internacao_id'))

    op.drop_table('evolucoes_medicas')
    with op.batch_alter_table('evolucoes_enfermagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolucoes_enfermagem_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_evolucoes_enfermagem_internacao_id'))

    op.drop_table('evolucoes_enfermagem')
    with op.batch_alter_table('controles_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controles_paciente_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_controles_paciente_internacao_id'))

    op.drop_table('controles_paciente')
    with op.batch_alter_table('internacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internacoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_internacoes_numero'))
        batch_op.drop_index(batch_op.f('ix_internacoes_admissao_em'))

    op.drop_table('internacoes')
    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leitos_status'))
        batch_op.drop_index(batch_op.f('ix_leitos_numero'))

    op.drop_table('leitos')
    # ### end Alembic commands ###
