"""add pdf_path to prescricoes_enfermagem e evolucoes_enfermagem

Revision ID: 75fb9b22d82e
Revises: d125303c4dd3
Create Date: 2026-08-28 18:22:51.923350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fb9b22d82e'
down_revision = 'd125303c4dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evolucoes_enfermagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('prescricoes_enfermagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricoes_enfermagem', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    with op.batch_alter_table('evolucoes_enfermagem', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
