"""add fase 4 apoio clinico (certificado, exames, farmacia, nutricao, ccih, cirurgias, maternidade)

Revision ID: d125303c4dd3
Revises: 5a50c2fd4cf2
Create Date: 2026-08-28 17:48:17.065574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd125303c4dd3'
down_revision = '5a50c2fd4cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('LABORATORIAL', 'IMAGEM', 'ANATOMOPATOLOGICO', 'CARDIOLOGICO', 'ENDOSCOPICO', 'OUTRO', name='categoriaexame'), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('valor_referencia', sa.String(length=200), nullable=True),
    sa.Column('prazo_horas', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exames_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exames_catalogo_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_exames_catalogo_nome'), ['nome'], unique=False)

    op.create_table('medicamentos_farmacia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('principio_ativo', sa.String(length=200), nullable=True),
    sa.Column('concentracao', sa.String(length=100), nullable=True),
    sa.Column('forma', sa.Enum('COMPRIMIDO', 'CAPSULA', 'AMPOLA', 'FRASCO', 'FRASCO_AMPOLA', 'BOLSA', 'TUBO', 'SACHE', 'SOLUCAO', 'POMADA', 'SUPOSITORIO', 'OUTRO', name='formafarmaceutica'), nullable=True),
    sa.Column('unidade_dispensacao', sa.String(length=50), nullable=True),
    sa.Column('controlado', sa.Boolean(), nullable=True),
    sa.Column('tipo_receituario', sa.String(length=50), nullable=True),
    sa.Column('codigo_sus', sa.String(length=20), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicamentos_farmacia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicamentos_farmacia_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicamentos_farmacia_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicamentos_farmacia_principio_ativo'), ['principio_ativo'], unique=False)

    op.create_table('salas_cirurgicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lotes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('fabricante', sa.String(length=150), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos_farmacia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_estoque_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lotes_estoque_validade'), ['validade'], unique=False)

    op.create_table('certificados_digitais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('A1', 'A3', 'TESTE', name='tipocertificado'), nullable=False),
    sa.Column('titular', sa.String(length=300), nullable=True),
    sa.Column('emissor', sa.String(length=300), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('valido_de', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificados_digitais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_digitais_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('documentos_assinados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_validacao', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.Enum('PRESCRICAO_MEDICA', 'EVOLUCAO_MEDICA', 'LAUDO_ALTA', 'LAUDO_EXAME', 'DESCRICAO_CIRURGICA', 'RECEITUARIO', 'ATESTADO', 'OUTRO', name='tipodocumentoassinado'), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('hash_documento', sa.String(length=128), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('qrcode_path', sa.String(length=500), nullable=True),
    sa.Column('assinante_id', sa.Integer(), nullable=False),
    sa.Column('assinante_nome', sa.String(length=300), nullable=True),
    sa.Column('certificado_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('origem_tipo', sa.String(length=50), nullable=True),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ASSINADO', 'INVALIDADO', 'REVOGADO', name='statusdocumento'), nullable=False),
    sa.Column('assinado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assinante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados_digitais.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_assinados_assinado_em'), ['assinado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_codigo_validacao'), ['codigo_validacao'], unique=True)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_hash_documento'), ['hash_documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('prenatais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestante_id', sa.Integer(), nullable=False),
    sa.Column('dum', sa.Date(), nullable=True),
    sa.Column('dpp', sa.Date(), nullable=True),
    sa.Column('gestacoes', sa.Integer(), nullable=True),
    sa.Column('partos', sa.Integer(), nullable=True),
    sa.Column('abortos', sa.Integer(), nullable=True),
    sa.Column('cesareas', sa.Integer(), nullable=True),
    sa.Column('classificacao_risco', sa.Enum('HABITUAL', 'ALTO_RISCO', name='classificacaorisco'), nullable=False),
    sa.Column('tipo_sanguineo', sa.String(length=5), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prenatais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prenatais_gestante_id'), ['gestante_id'], unique=False)

    op.create_table('consultas_prenatal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenatal_id', sa.Integer(), nullable=False),
    sa.Column('data_consulta', sa.Date(), nullable=False),
    sa.Column('idade_gestacional_semanas', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pressao_arterial', sa.String(length=20), nullable=True),
    sa.Column('altura_uterina', sa.Integer(), nullable=True),
    sa.Column('bcf', sa.Integer(), nullable=True),
    sa.Column('movimentacao_fetal', sa.Boolean(), nullable=True),
    sa.Column('edema', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prenatal_id'], ['prenatais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas_prenatal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_prenatal_prenatal_id'), ['prenatal_id'], unique=False)

    op.create_table('cirurgias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('cirurgiao_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('procedimento', sa.String(length=300), nullable=False),
    sa.Column('codigo_procedimento', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('ELETIVA', 'URGENCIA', 'EMERGENCIA', name='tipocirurgia'), nullable=False),
    sa.Column('porte', sa.Enum('PEQUENO', 'MEDIO', 'GRANDE', 'ESPECIAL', name='portecirurgico'), nullable=True),
    sa.Column('tipo_anestesia', sa.Enum('GERAL', 'RAQUIDIANA', 'PERIDURAL', 'LOCAL', 'SEDACAO', 'BLOQUEIO', name='tipoanestesia'), nullable=True),
    sa.Column('cid10', sa.String(length=10), nullable=True),
    sa.Column('indicacao', sa.String(length=500), nullable=True),
    sa.Column('lateralidade', sa.String(length=20), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_estimada_min', sa.Integer(), nullable=True),
    sa.Column('anestesista_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADA', 'AGENDADA', 'CONFIRMADA', 'EM_PREPARO', 'EM_ANDAMENTO', 'RECUPERACAO', 'CONCLUIDA', 'CANCELADA', 'SUSPENSA', name='statuscirurgia'), nullable=False),
    sa.Column('entrada_sala_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inicio_cirurgia_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fim_cirurgia_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saida_sala_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descricao_cirurgica', sa.Text(), nullable=True),
    sa.Column('achados', sa.Text(), nullable=True),
    sa.Column('procedimento_realizado', sa.Text(), nullable=True),
    sa.Column('intercorrencias', sa.Text(), nullable=True),
    sa.Column('equipe', sa.Text(), nullable=True),
    sa.Column('material_utilizado', sa.Text(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=300), nullable=True),
    sa.Column('descricao_assinada', sa.Boolean(), nullable=True),
    sa.Column('documento_assinado_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anestesista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cirurgiao_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['documento_assinado_id'], ['documentos_assinados.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas_cirurgicas.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cirurgias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cirurgias_data_agendada'), ['data_agendada'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_cirurgias_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_status'), ['status'], unique=False)

    op.create_table('notificacoes_infeccao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('notificante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('IRAS', 'COMUNITARIA', 'SITIO_CIRURGICO', 'TRATO_URINARIO', 'CORRENTE_SANGUINEA', 'PNEUMONIA', 'PELE_PARTES_MOLES', 'OUTRA', name='tipoinfeccao'), nullable=False),
    sa.Column('topografia', sa.String(length=200), nullable=True),
    sa.Column('microrganismo', sa.String(length=200), nullable=True),
    sa.Column('antibiograma', sa.Text(), nullable=True),
    sa.Column('cid10', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_INVESTIGACAO', 'CONFIRMADA', 'DESCARTADA', 'ENCERRADA', name='statusnotificacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('conduta', sa.Text(), nullable=True),
    sa.Column('data_notificacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_encerramento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['notificante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes_infeccao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_infeccao_data_notificacao'), ['data_notificacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_infeccao_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_notificacoes_infeccao_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_infeccao_status'), ['status'], unique=False)

    op.create_table('partos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('gestante_id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('prenatal_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('NORMAL', 'CESAREA', 'FORCEPS', 'VACUO', name='tipoparto'), nullable=False),
    sa.Column('data_parto', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idade_gestacional_semanas', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_anestesia', sa.String(length=50), nullable=True),
    sa.Column('intercorrencias', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prenatal_id'], ['prenatais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partos_data_parto'), ['data_parto'], unique=False)
        batch_op.create_index(batch_op.f('ix_partos_gestante_id'), ['gestante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partos_numero'), ['numero'], unique=True)

    op.create_table('prescricoes_dieteticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('nutricionista_id', sa.Integer(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=False),
    sa.Column('tipo_dieta', sa.Enum('LIVRE', 'BRANDA', 'PASTOSA', 'LIQUIDA', 'LIQUIDA_RESTRITA', 'LEVE', 'ZERO_JEJUM', 'ENTERAL', 'PARENTERAL', 'HIPOSSODICA', 'DIABETICO', 'HIPOPROTEICA', 'HIPERPROTEICA', 'INFANTIL', 'OUTRA', name='tipodieta'), nullable=False),
    sa.Column('consistencia', sa.Enum('NORMAL', 'BRANDA', 'PASTOSA', 'LIQUIDA', 'LIQUIDA_COMPLETA', name='consistenciadieta'), nullable=True),
    sa.Column('via', sa.Enum('ORAL', 'SONDA_NASOGASTRICA', 'SONDA_NASOENTERAL', 'GASTROSTOMIA', 'JEJUNOSTOMIA', 'PARENTERAL', name='viaalimentacao'), nullable=False),
    sa.Column('valor_calorico', sa.Integer(), nullable=True),
    sa.Column('fracionamento', sa.String(length=100), nullable=True),
    sa.Column('restricoes', sa.String(length=300), nullable=True),
    sa.Column('suplementos', sa.String(length=300), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'SUSPENSA', 'ENCERRADA', name='statusprescricaodieta'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescricoes_dieteticas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_dieteticas_internacao_id'), ['internacao_id'], unique=False)

    op.create_table('solicitacoes_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('AMBULATORIO', 'EMERGENCIA', 'INTERNACAO', name='origemexame'), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('atendimento_emergencia_id', sa.Integer(), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.Enum('ROTINA', 'URGENTE', 'EMERGENCIA', name='prioridadeexame'), nullable=False),
    sa.Column('status', sa.Enum('SOLICITADO', 'COLETADO', 'EM_ANALISE', 'RESULTADO_DISPONIVEL', 'CANCELADO', name='statussolicitacaoexame'), nullable=False),
    sa.Column('indicacao_clinica', sa.String(length=500), nullable=True),
    sa.Column('cid10', sa.String(length=10), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('solicitado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coletado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_emergencia_id'], ['atendimentos_emergencia.id'], ),
    sa.ForeignKeyConstraint(['coletado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_ambulatoriais.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes_exame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_exame_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_solicitacoes_exame_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_exame_solicitado_em'), ['solicitado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_exame_status'), ['status'], unique=False)

    op.create_table('dispensacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('prescricao_id', sa.Integer(), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'DISPENSADO', 'PARCIAL', 'CANCELADO', name='statusdispensacao'), nullable=False),
    sa.Column('farmaceutico_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('dispensado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmaceutico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes_medicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispensacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispensacoes_dispensado_em'), ['dispensado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensacoes_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispensacoes_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensacoes_prescricao_id'), ['prescricao_id'], unique=False)

    op.create_table('isolamentos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('notificacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo_precaucao', sa.Enum('PADRAO', 'CONTATO', 'GOTICULAS', 'AEROSSOIS', 'PROTETORA', name='tipoprecaucao'), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('microrganismo', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'ENCERRADO', name='statusisolamento'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prescrito_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacoes_infeccao.id'], ),
    sa.ForeignKeyConstraint(['prescrito_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('isolamentos_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_isolamentos_paciente_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_isolamentos_paciente_status'), ['status'], unique=False)

    op.create_table('itens_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('exame_catalogo_id', sa.Integer(), nullable=True),
    sa.Column('nome_exame', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['exame_catalogo_id'], ['exames_catalogo.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_exame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_exame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_exame_solicitacao_id'), ['solicitacao_id'], unique=False)

    op.create_table('recem_nascidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parto_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', 'INDETERMINADO', name='sexorn'), nullable=False),
    sa.Column('condicao', sa.Enum('VIVO', 'NATIMORTO', 'OBITO_PERINATAL', name='condicaonascimento'), nullable=False),
    sa.Column('peso_gramas', sa.Integer(), nullable=True),
    sa.Column('comprimento_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('perimetro_cefalico_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('apgar_1min', sa.Integer(), nullable=True),
    sa.Column('apgar_5min', sa.Integer(), nullable=True),
    sa.Column('hora_nascimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reanimacao', sa.Boolean(), nullable=True),
    sa.Column('intercorrencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['parto_id'], ['partos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recem_nascidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recem_nascidos_parto_id'), ['parto_id'], unique=False)

    op.create_table('itens_dispensacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispensacao_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('item_prescricao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispensacao_id'], ['dispensacoes.id'], ),
    sa.ForeignKeyConstraint(['item_prescricao_id'], ['itens_prescricao.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_estoque.id'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos_farmacia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_dispensacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_dispensacao_dispensacao_id'), ['dispensacao_id'], unique=False)

    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'DISPENSACAO', 'AJUSTE', 'DEVOLUCAO', 'PERDA', 'VENCIMENTO', 'TRANSFERENCIA', name='tipomovimentoestoque'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('saldo_apos', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('dispensacao_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispensacao_id'], ['dispensacoes.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_estoque.id'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos_farmacia.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('resultados_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('valor_referencia', sa.String(length=200), nullable=True),
    sa.Column('laudo', sa.Text(), nullable=True),
    sa.Column('alterado', sa.Boolean(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('liberado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assinado', sa.Boolean(), nullable=True),
    sa.Column('documento_assinado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_assinado_id'], ['documentos_assinados.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens_exame.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_exame')
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_medicamento_id'))

    op.drop_table('movimentos_estoque')
    with op.batch_alter_table('itens_dispensacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_dispensacao_dispensacao_id'))

    op.drop_table('itens_dispensacao')
    with op.batch_alter_table('recem_nascidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recem_nascidos_parto_id'))

    op.drop_table('recem_nascidos')
    with op.batch_alter_table('itens_exame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_exame_solicitacao_id'))

    op.drop_table('itens_exame')
    with op.batch_alter_table('isolamentos_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_isolamentos_paciente_status'))
        batch_op.drop_index(batch_op.f('ix_isolamentos_paciente_internacao_id'))

    op.drop_table('isolamentos_paciente')
    with op.batch_alter_table('dispensacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispensacoes_prescricao_id'))
        batch_op.drop_index(batch_op.f('ix_dispensacoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_dispensacoes_numero'))
        batch_op.drop_index(batch_op.f('ix_dispensacoes_dispensado_em'))

    op.drop_table('dispensacoes')
    with op.batch_alter_table('solicitacoes_exame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_exame_status'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_exame_solicitado_em'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_exame_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_exame_numero'))

    op.drop_table('solicitacoes_exame')
    with op.batch_alter_table('prescricoes_dieteticas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_dieteticas_internacao_id'))

    op.drop_table('prescricoes_dieteticas')
    with op.batch_alter_table('partos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partos_numero'))
        batch_op.drop_index(batch_op.f('ix_partos_gestante_id'))
        batch_op.drop_index(batch_op.f('ix_partos_data_parto'))

    op.drop_table('partos')
    with op.batch_alter_table('notificacoes_infeccao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_infeccao_status'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_infeccao_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_infeccao_numero'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_infeccao_data_notificacao'))

    op.drop_table('notificacoes_infeccao')
    with op.batch_alter_table('cirurgias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cirurgias_status'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_numero'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_data_agendada'))

    op.drop_table('cirurgias')
    with op.batch_alter_table('consultas_prenatal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_prenatal_prenatal_id'))

    op.drop_table('consultas_prenatal')
    with op.batch_alter_table('prenatais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prenatais_gestante_id'))

    op.drop_table('prenatais')
    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_hash_documento'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_codigo_validacao'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_assinado_em'))

    op.drop_table('documentos_assinados')
    with op.batch_alter_table('certificados_digitais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_digitais_usuario_id'))

    op.drop_table('certificados_digitais')
    with op.batch_alter_table('lotes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_estoque_validade'))
        batch_op.drop_index(batch_op.f('ix_lotes_estoque_medicamento_id'))

    op.drop_table('lotes_estoque')
    op.drop_table('salas_cirurgicas')
    with op.batch_alter_table('medicamentos_farmacia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicamentos_farmacia_principio_ativo'))
        batch_op.drop_index(batch_op.f('ix_medicamentos_farmacia_nome'))
        batch_op.drop_index(batch_op.f('ix_medicamentos_farmacia_codigo'))

    op.drop_table('medicamentos_farmacia')
    with op.batch_alter_table('exames_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exames_catalogo_nome'))
        batch_op.drop_index(batch_op.f('ix_exames_catalogo_codigo'))

    op.drop_table('exames_catalogo')
    # ### end Alembic commands ###
