"""S-07 trilha de auditoria (logs_acesso) e criado_por_id NOT NULL

Revision ID: d8cb1d8248c9
Revises: 352f70fe1d77
Create Date: 2026-08-28 23:58:52.905199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cb1d8248c9'
down_revision = '352f70fe1d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_acesso',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_username', sa.String(length=50), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.Enum('VISUALIZAR', 'BAIXAR_DOCUMENTO', 'EXPORTAR', name='acaoauditoria'), nullable=False),
    sa.Column('recurso', sa.String(length=120), nullable=False),
    sa.Column('recurso_id', sa.String(length=60), nullable=True),
    sa.Column('detalhe', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_acesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_acesso_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_acesso_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_acesso_registrado_em'), ['registrado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_acesso_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('criado_por_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('criado_por_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('logs_acesso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_acesso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_logs_acesso_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_logs_acesso_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_logs_acesso_acao'))

    op.drop_table('logs_acesso')
    # ### end Alembic commands ###
