"""add fase 5 administrativo (estoque, compras, financeiro, faturamento, convenios, patrimonio, rh, manutencao)

Revision ID: f26b8ccb9b91
Revises: 75fb9b22d82e
Create Date: 2026-08-28 19:14:29.578887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b8ccb9b91'
down_revision = '75fb9b22d82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bens_patrimoniais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_patrimonio', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=150), nullable=True),
    sa.Column('situacao', sa.Enum('ATIVO', 'EM_MANUTENCAO', 'BAIXADO', 'EMPRESTADO', 'INSERVIVEL', name='situacaobem'), nullable=False),
    sa.Column('estado', sa.Enum('NOVO', 'BOM', 'REGULAR', 'RUIM', 'PESSIMO', name='estadoconservacao'), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('vida_util_anos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bens_patrimoniais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bens_patrimoniais_numero_patrimonio'), ['numero_patrimonio'], unique=True)
        batch_op.create_index(batch_op.f('ix_bens_patrimoniais_situacao'), ['situacao'], unique=False)

    op.create_table('categorias_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipolancamento'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('registro_ans', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('tabela_preco', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convenios_nome'), ['nome'], unique=True)

    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_fornecedores_razao_social'), ['razao_social'], unique=False)

    op.create_table('locais_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('procedimentos_cbhpm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('porte', sa.String(length=20), nullable=True),
    sa.Column('valor_referencia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedimentos_cbhpm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedimentos_cbhpm_codigo'), ['codigo'], unique=True)

    op.create_table('procedimentos_sigtap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('complexidade', sa.String(length=50), nullable=True),
    sa.Column('valor_sus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedimentos_sigtap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedimentos_sigtap_codigo'), ['codigo'], unique=True)

    op.create_table('produtos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.Enum('MEDICAMENTO', 'MATERIAL_MEDICO', 'MATERIAL_LIMPEZA', 'GENERO_ALIMENTICIO', 'EXPEDIENTE', 'ROUPARIA', 'OUTRO', name='categoriaproduto'), nullable=False),
    sa.Column('unidade', sa.Enum('UNIDADE', 'CAIXA', 'FRASCO', 'AMPOLA', 'PACOTE', 'LITRO', 'MILILITRO', 'GRAMA', 'QUILO', 'METRO', 'PAR', name='unidademedida'), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('estoque_maximo', sa.Integer(), nullable=True),
    sa.Column('valor_medio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_estoque_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_estoque_nome'), ['nome'], unique=False)

    op.create_table('saldos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'local_id', name='uq_saldo_produto_local')
    )
    with op.batch_alter_table('saldos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldos_estoque_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saldos_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_CONTAGEM', 'FECHADO', name='statusinventario'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_bem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bem_id', sa.Integer(), nullable=False),
    sa.Column('localizacao_origem', sa.String(length=150), nullable=True),
    sa.Column('localizacao_destino', sa.String(length=150), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bem_id'], ['bens_patrimoniais.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacoes_bem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_bem_bem_id'), ['bem_id'], unique=False)

    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('CORRETIVA', 'PREVENTIVA', 'PREDITIVA', 'INSTALACAO', name='tipomanutencao'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadeos'), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_EXECUCAO', 'AGUARDANDO_PECA', 'CONCLUIDA', 'CANCELADA', name='statusos'), nullable=False),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('bem_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('aberta_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('custo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preventiva_intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('proxima_preventiva', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bem_id'], ['bens_patrimoniais.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_aberta_em'), ['aberta_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_ordens_servico_prioridade'), ['prioridade'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_status'), ['status'], unique=False)

    op.create_table('requisicoes_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('setor_solicitante', sa.String(length=100), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('local_atendimento_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ATENDIDA', 'PARCIAL', 'CANCELADA', name='statusrequisicao'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atendida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atendida_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendida_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['local_atendimento_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisicoes_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requisicoes_material_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisicoes_material_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_requisicoes_material_status'), ['status'], unique=False)

    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('solicitacoes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_COTACAO', 'APROVADA', 'PEDIDO_EMITIDO', 'RECEBIDA', 'CANCELADA', name='statussolicitacaocompra'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_compra_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_compra_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_solicitacoes_compra_status'), ['status'], unique=False)

    op.create_table('cotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('condicao_pagamento', sa.String(length=100), nullable=True),
    sa.Column('vencedora', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotacoes_solicitacao_id'), ['solicitacao_id'], unique=False)

    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('vinculo', sa.Enum('CLT', 'ESTATUTARIO', 'PJ', 'TEMPORARIO', 'ESTAGIARIO', 'VOLUNTARIO', name='tipovinculo'), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'FERIAS', 'AFASTADO', 'DESLIGADO', name='statusfuncionario'), nullable=False),
    sa.Column('conselho_tipo', sa.String(length=10), nullable=True),
    sa.Column('conselho_numero', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_funcionarios_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionarios_status'), ['status'], unique=False)

    op.create_table('itens_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('saldo_sistema', sa.Integer(), nullable=True),
    sa.Column('contagem_fisica', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_inventario_inventario_id'), ['inventario_id'], unique=False)

    op.create_table('itens_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
    sa.Column('quantidade_atendida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_requisicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_requisicao_requisicao_id'), ['requisicao_id'], unique=False)

    op.create_table('itens_solicitacao_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_solicitacao_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_solicitacao_compra_solicitacao_id'), ['solicitacao_id'], unique=False)

    op.create_table('movimentos_estoque_almox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('local_destino_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'TRANSFERENCIA', 'AJUSTE', 'PERDA', 'INVENTARIO', name='tipomovimento'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes_material.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque_almox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_almox_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_almox_registrado_em'), ['registrado_em'], unique=False)

    op.create_table('escalas_plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.Enum('MANHA', 'TARDE', 'NOITE', 'DIURNO_12', 'NOTURNO_12', 'PLANTAO_24', name='turnoplantao'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalas_plantao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalas_plantao_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalas_plantao_funcionario_id'), ['funcionario_id'], unique=False)

    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('cotacao_id', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('EMITIDO', 'PARCIAL', 'RECEBIDO', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('emitido_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacoes.id'], ),
    sa.ForeignKeyConstraint(['emitido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_compra_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_status'), ['status'], unique=False)

    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.Enum('PAGAR', 'RECEBER', name='tipoconta'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'PAGA', 'RECEBIDA', 'ATRASADA', 'CANCELADA', name='statusconta'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('pedido_compra_id', sa.Integer(), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido_compra_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_vencimento'), ['vencimento'], unique=False)

    op.create_table('guias_convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('CONSULTA', 'SP_SADT', 'INTERNACAO', 'HONORARIO', name='tipoguia'), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('numero_carteirinha', sa.String(length=50), nullable=True),
    sa.Column('senha_autorizacao', sa.String(length=50), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_glosado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'ENVIADA', 'AUTORIZADA', 'GLOSADA', 'PAGA', 'NEGADA', name='statusguia'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_ambulatoriais.id'], ),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guias_convenio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guias_convenio_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_convenio_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_guias_convenio_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_convenio_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_convenio_tipo'), ['tipo'], unique=False)

    op.create_table('guias_faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('AIH', 'APAC', 'BPA_I', 'BPA_C', name='tipoproducao'), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.String(length=6), nullable=False),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('procedimento_principal', sa.String(length=15), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_aih_apac', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', 'EXPORTADA', 'GLOSADA', 'PAGA', name='statusfaturamento'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_ambulatoriais.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guias_faturamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guias_faturamento_competencia'), ['competencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_faturamento_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_guias_faturamento_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_faturamento_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guias_faturamento_tipo'), ['tipo'], unique=False)

    op.create_table('itens_pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_recebida', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_compra_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('recebimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('recebido_por_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locais_estoque.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.ForeignKeyConstraint(['recebido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recebimentos_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recebimentos_recebido_em'), ['recebido_em'], unique=False)

    op.create_table('itens_guia_convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=True),
    sa.Column('codigo_procedimento', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['guia_id'], ['guias_convenio.id'], ),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimentos_cbhpm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_guia_convenio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_guia_convenio_guia_id'), ['guia_id'], unique=False)

    op.create_table('itens_guia_faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=True),
    sa.Column('codigo_procedimento', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['guia_id'], ['guias_faturamento.id'], ),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimentos_sigtap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_guia_faturamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_guia_faturamento_guia_id'), ['guia_id'], unique=False)

    op.create_table('lancamentos_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipolancamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_caixa_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_caixa_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_caixa_tipo'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_caixa_data'))

    op.drop_table('lancamentos_caixa')
    with op.batch_alter_table('itens_guia_faturamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_guia_faturamento_guia_id'))

    op.drop_table('itens_guia_faturamento')
    with op.batch_alter_table('itens_guia_convenio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_guia_convenio_guia_id'))

    op.drop_table('itens_guia_convenio')
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recebimentos_recebido_em'))
        batch_op.drop_index(batch_op.f('ix_recebimentos_pedido_id'))

    op.drop_table('recebimentos')
    with op.batch_alter_table('itens_pedido_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_compra_pedido_id'))

    op.drop_table('itens_pedido_compra')
    with op.batch_alter_table('guias_faturamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guias_faturamento_tipo'))
        batch_op.drop_index(batch_op.f('ix_guias_faturamento_status'))
        batch_op.drop_index(batch_op.f('ix_guias_faturamento_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_guias_faturamento_numero'))
        batch_op.drop_index(batch_op.f('ix_guias_faturamento_competencia'))

    op.drop_table('guias_faturamento')
    with op.batch_alter_table('guias_convenio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guias_convenio_tipo'))
        batch_op.drop_index(batch_op.f('ix_guias_convenio_status'))
        batch_op.drop_index(batch_op.f('ix_guias_convenio_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_guias_convenio_numero'))
        batch_op.drop_index(batch_op.f('ix_guias_convenio_criado_em'))

    op.drop_table('guias_convenio')
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_vencimento'))
        batch_op.drop_index(batch_op.f('ix_contas_tipo'))
        batch_op.drop_index(batch_op.f('ix_contas_status'))

    op.drop_table('contas')
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_status'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_numero'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_criado_em'))

    op.drop_table('pedidos_compra')
    with op.batch_alter_table('escalas_plantao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalas_plantao_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_escalas_plantao_data'))

    op.drop_table('escalas_plantao')
    with op.batch_alter_table('movimentos_estoque_almox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_almox_registrado_em'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_almox_produto_id'))

    op.drop_table('movimentos_estoque_almox')
    with op.batch_alter_table('itens_solicitacao_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_solicitacao_compra_solicitacao_id'))

    op.drop_table('itens_solicitacao_compra')
    with op.batch_alter_table('itens_requisicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_requisicao_requisicao_id'))

    op.drop_table('itens_requisicao')
    with op.batch_alter_table('itens_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_inventario_inventario_id'))

    op.drop_table('itens_inventario')
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_status'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_nome'))
        batch_op.drop_index(batch_op.f('ix_funcionarios_matricula'))

    op.drop_table('funcionarios')
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotacoes_solicitacao_id'))

    op.drop_table('cotacoes')
    with op.batch_alter_table('solicitacoes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_compra_status'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_compra_numero'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_compra_criado_em'))

    op.drop_table('solicitacoes_compra')
    op.drop_table('setores')
    with op.batch_alter_table('requisicoes_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisicoes_material_status'))
        batch_op.drop_index(batch_op.f('ix_requisicoes_material_numero'))
        batch_op.drop_index(batch_op.f('ix_requisicoes_material_criado_em'))

    op.drop_table('requisicoes_material')
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_status'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_prioridade'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_numero'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_aberta_em'))

    op.drop_table('ordens_servico')
    with op.batch_alter_table('movimentacoes_bem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_bem_bem_id'))

    op.drop_table('movimentacoes_bem')
    op.drop_table('inventarios')
    with op.batch_alter_table('saldos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saldos_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_saldos_estoque_local_id'))

    op.drop_table('saldos_estoque')
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_estoque_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_estoque_codigo'))

    op.drop_table('produtos_estoque')
    with op.batch_alter_table('procedimentos_sigtap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedimentos_sigtap_codigo'))

    op.drop_table('procedimentos_sigtap')
    with op.batch_alter_table('procedimentos_cbhpm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedimentos_cbhpm_codigo'))

    op.drop_table('procedimentos_cbhpm')
    op.drop_table('locais_estoque')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_razao_social'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_cnpj'))

    op.drop_table('fornecedores')
    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convenios_nome'))

    op.drop_table('convenios')
    op.drop_table('categorias_financeiras')
    with op.batch_alter_table('bens_patrimoniais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bens_patrimoniais_situacao'))
        batch_op.drop_index(batch_op.f('ix_bens_patrimoniais_numero_patrimonio'))

    op.drop_table('bens_patrimoniais')
    # ### end Alembic commands ###
